image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/
    - .venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate

stages:
  - validate
  - build
  - deploy

# 验证文档格式
validate:
  stage: validate
  script:
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - site/
    expire_in: 1 hour
  only:
    - merge_requests

# 构建并部署到 GitLab Pages
pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main