name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 设置 GitHub Token 权限
permissions:
  contents: write
  pages: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Restore cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ hashFiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-
            
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force --config-file mkdocs.yml